#!/bin/bash
set -e

script_path="`dirname $0`"
rm -rf CMakeCache.txt CMakeFiles Makefile cmake_install.cmake

PATH=$PATH \
cmake src \
-DARCH=core2 \
-DOLD_DWARF_FORMAT=1 \
-DCMAKE_EXE_LINKER_FLAGS='-Wl,-rpath,$PATH'

make -j4

rm -rf CMakeCache.txt CMakeFiles Makefile cmake_install.cmake
